name: "EQ8"
description: "mydigitalcollege student app"
publish_to: "none"
version: "1.9.5+19"
environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: "flutter"
  cupertino_icons: "^1.0.6"
  lottie: "^3.0.0"
  video_player: "^2.6.0"
  dashed_rect: "^0.0.4"
  animations: "^2.0.8"
  fluttertoast: "^8.2.2"
  shared_preferences: "^2.2.1"
  flutter_secure_storage: "^9.2.2"
  loader_overlay: "^4.0.0"
  flutter_spinkit: "^5.2.0"
  flutter_cache_manager: "^3.3.1"
  flutter_animation_progress_bar: "^2.3.1"
  connectivity_plus: "^6.0.1"
  http: "^1.0.0"
  url_launcher: "^6.1.14"
  flick_video_player: "^0.9.0"
  video_player_win: "^2.3.11"
  flutter_launcher_icons: "^0.13.1"
  device_info_plus: "^11.0.0"
  pdfrx: "^2.4.7"
  google_fonts: "^8.0.0"
  window_manager: "^0.3.8"
  webview_flutter: "^4.8.0"
  webview_windows: "^0.4.0"
  flutter_tts: "^4.0.2"
  speech_to_text: "^7.0.0"
  chat_gpt_sdk: "^3.0.4"
  image_picker: "^1.1.2"
  flutter_markdown: "^0.7.4+1"
  flutter_math_fork: "^0.7.4"
  flutter_markdown_latex: "^0.3.4"
  just_audio: "^0.9.42"
  audioplayers: "^6.0.0"
  fl_chart: "^0.65.0"
  intl: "^0.20.2"
  animated_text_kit: "^4.2.3"
  inno_build: "^0.4.0"
dev_dependencies:
  flutter_test:
    sdk: "flutter"
  flutter_lints: "^4.0.0"
  msix: "^3.16.7"
flutter:
  uses-material-design: true
  assets:
    - "assets/Images/"
    - "assets/Images/BG/"
    - "assets/Images/Icons/subjects/"
    - "assets/Images/Icons/"
    - "assets/Data/"
    - "assets/html/"
  fonts:
    - family: "Lato"
      fonts:
        - asset: "assets/google_fonts/Lato/Lato-Regular.ttf"
        - asset: "assets/google_fonts/Lato/Lato-Italic.ttf"
          style: "italic"
        - asset: "assets/google_fonts/Lato/Lato-Bold.ttf"
          weight: 800
msix_config:
  display_name: "EQ8"
  publisher_display_name: "MyDigitalCollege"
  identity_name: "com.pg.eq8"
  msix_version: "1.0.0.0"
  logo_path: "D:\\Mobile\\eq8\\assets\\logo.png"
  capabilities: "internetClient, location, microphone, webcam"
inno_build:
  app_id: "0bf0a0a1-2743-4048-9bd6-36e48892a4d0"
